name: rick-morty-explorer

services:
  backend:
    build: ./backend
    environment:
      PORT: 3000
      API: https://rickandmortyapi.com/api
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_URL: ${BACKEND_URL:-http://localhost:3000}
    ports:
      - "8080:80"
    depends_on:
      - backend
